Repository olive-editor/olive, pull requests merged in 2020-10, with the labels that each got.

#1262 Fix #1252
  app/render/audioplaybackcache.cpp
Labels: hacktoberfest-accepted

#1269 Fix building without OTIO support
  app/codec/CMakeLists.txt
  app/codec/decoder.cpp
  app/core.cpp
  app/task/project/CMakeLists.txt
Labels: hacktoberfest-accepted

#1272 Fix #1271 Duplicate Keyframed Node
  app/node/input.cpp
Labels: hacktoberfest-accepted

#1278 Docker: Add ci-otio image
  docker/ci-common/Dockerfile
  docker/ci-crashpad/Dockerfile
  docker/ci-ffmpeg/Dockerfile
  docker/ci-olive/Dockerfile
  docker/ci-otio/Dockerfile
  docker/scripts/build_otio.sh
Labels: Building/Packaging, Project Management, hacktoberfest-accepted

#1279 Docker: Add more & update libraries for FFmpeg
  docker/README.md
  docker/ci-ffmpeg/Dockerfile
  docker/scripts/build_ffmpeg.sh
  docker/scripts/common/install_yumpackages.sh
Labels: Building/Packaging, hacktoberfest-accepted
