Repository olive-editor/olive, pull requests merged in 2020-11, with the labels that each got.

#1312 [UI] update "New" icon with a right bottom triangle
  app/ui/style/olive-dark/png/new.128.png
  app/ui/style/olive-dark/png/new.16.png
  app/ui/style/olive-dark/png/new.32.png
  app/ui/style/olive-dark/png/new.64.png
  app/ui/style/olive-dark/svg/new.svg
  app/ui/style/olive-light/png/new.128.png
  app/ui/style/olive-light/png/new.16.png
  app/ui/style/olive-light/png/new.32.png
  app/ui/style/olive-light/png/new.64.png
  app/ui/style/olive-light/svg/new.svg
Labels: User Interface

#1291 Remove old Travis and AppVeyor CI, update .gitignore
  .appveyor/build.bat
  .gitignore
  .travis.yml
  .travis/after_success.sh
  .travis/before_install.sh
  .travis/install.sh
  .travis/script.sh
  appveyor.yml
Labels: Building/Packaging, Continuous Integration

#1332 Docker: Add own ci-ocio image for OpenColorIO v2
  docker/ci-ocio/Dockerfile
  docker/ci-olive/Dockerfile
  docker/scripts/build_ocio.sh
Labels: Continuous Integration

#1383 Simplified Chinese Translation
  app/ts/zh_CN.ts
Labels: Translation

#1416 Improved translation
  app/ts/zh_CN.ts
Labels: Translation
