Repository olive-editor/olive, pull requests merged in 2021-03, with the labels that each got.

#1484 Update zh_CN.ts
  app/ts/zh_CN.ts
Labels: Translation

#1499 Update zh_CN.ts
  app/ts/zh_CN.ts
Labels: Translation

#1442 Update Russian translation
  app/ts/ru_RU.ts
Labels: Translation

#1433 Update zh_CN translation
  app/ts/zh_CN.ts
Labels: Translation

#1513 Update french translation
  app/ts/fr_FR.ts
Labels: Translation

#1485 Update Spanish translation
  app/ts/es_ES.ts
Labels: Translation

#1434 cmake: misc macOS fixes
  .github/workflows/ci.yml
  CMakeLists.txt
  app/CMakeLists.txt
  app/packaging/macos/MacOSXBundleInfo.plist.in
Labels: Building/Packaging

#1521 Add QPainterPath include to fix compilation of 0.1.x
  effects/internal/texteffect.cpp
  effects/internal/timecodeeffect.cpp
  ui/graphview.cpp
  ui/timelineheader.cpp
Labels: Building/Packaging

#1489 Docker: Update build image with final OCIOv2
  .github/workflows/ci.yml
  cmake/FindOpenColorIO.cmake
  docker/README.md
  docker/ci-common/Dockerfile
  docker/ci-ffmpeg/Dockerfile
  docker/ci-ocio/Dockerfile
  docker/ci-olive/Dockerfile
  docker/ci-otio/Dockerfile
  docker/scripts/2/versions_common.sh
  docker/scripts/2021/versions_base.sh
  docker/scripts/build_crashpad.sh
  docker/scripts/build_ffmpeg.sh
  docker/scripts/build_ocio.sh
  docker/scripts/build_olive.sh
  docker/scripts/build_otio.sh
  docker/scripts/common/install_yumpackages.sh
Labels: Continuous Integration
