Repository olive-editor/olive, pull requests merged in 2021-04, with the labels that each got.

#1315 Add support for transitions when loading OTIO files
  app/task/project/loadotio/loadotio.cpp
Labels: Project Management

#1424 Fix plural handling for translations
  app/dialog/preferences/tabs/preferencesdisktab.cpp
  app/dialog/preferences/tabs/preferencesgeneraltab.cpp
  app/node/project/footage/footage.cpp
  app/task/project/import/import.cpp
  app/ts/en_US.ts
  app/widget/nodeparamview/nodeparamviewarraywidget.cpp
  app/widget/nodeparamview/nodeparamviewitem.cpp
  app/widget/slider/sliderbase.cpp
  app/widget/slider/sliderbase.h
  app/window/mainwindow/mainstatusbar.cpp
Labels: Translation

#1446 Rational slider
  app/node/block/block.cpp
  app/panel/timebased/timebased.cpp
  app/panel/timebased/timebased.h
  app/widget/menu/menushared.cpp
  app/widget/menu/menushared.h
  app/widget/nodeparamview/nodeparamview.cpp
  app/widget/nodeparamview/nodeparamviewitem.cpp
  app/widget/nodeparamview/nodeparamviewitem.h
  app/widget/nodeparamview/nodeparamviewwidgetbridge.cpp
  app/widget/nodeparamview/nodeparamviewwidgetbridge.h
  app/widget/slider/CMakeLists.txt
  app/widget/slider/rationalslider.cpp
  app/widget/slider/rationalslider.h
  app/widget/slider/sliderbase.cpp
  app/widget/slider/sliderbase.h
  app/widget/slider/sliderlabel.cpp
  app/widget/slider/sliderlabel.h
  app/widget/slider/sliderladder.cpp
  app/widget/slider/sliderladder.h
  app/widget/timeruler/timeruler.cpp
  app/window/mainwindow/mainmenu.cpp
Labels: User Interface
